### ISSUE TITLE
twigLinkResolver.loaderPaths is not working on windows

### ISSUE THREAD

**Issue by JeremyGiner** [Chaxwell/vscode-extension-twigLinkResolver#12]
I have the following settings :
```
"twigLinkResolver.loaderPaths": {
    "@App": "src\\Modules\\Views",
    ...
},
```

They do not seems to work on windows after a bit a debugging i think i found the problem.
src\main.ts line 70 :
 `return filePath.slice(0, nsLength + 1) === namespace + '/'`
should be : 
` return filePath.slice(0, nsLength + 1) === namespace + path.sep`
Since filePath seperator has already been replaced line 68

Can someone fix it ?

**Comment by Chaxwell** [comment]
Thank you for reporting the issue, I will look into it.
