### ISSUE TITLE
Links are not being generated

### ISSUE THREAD

**Issue by S-n-d** [Chaxwell/vscode-extension-twigLinkResolver#2]
Hi Chaxwell, great idea for a plugin! Exactly what I was searching for. Howerver, unfortunately it doesn't work on my machine. No links are generated.

VScode 1.71.0
MacOS 12.5 Monterey

**Comment by Chaxwell** [comment]
Hey, thank you for reporting an issue :)

Could you please make sure that your links pass this regex ?
https://regex101.com/r/zRthWB/1

**Comment by S-n-d** [comment]
Hey Chaxwell, thanks for looking into it! 

It appears the .html part is needed for the link to generate. So for example `"_partials/navigation/breadcrumbs.twig"` does not work but `"_partials/navigation/breadcrumbs.html.twig"` does.

Is there a reason the `.html` part is mandatory?

**Comment by Chaxwell** [comment]
No particular reason, that's just what I'm used to :)

I will make a patch of this before the end of this week.

**Comment by S-n-d** [comment]
Great! Looking forward to using your plugin. Thanks again :) 

Side note: sometimes I even ommit the .twig part, so `_partials/navigation/breadcrumbs` instead of `_partials/navigation/breadcrumbs.twig`. Don't know if it's possible to also make this work?

**Comment by Chaxwell** [comment]
Well I should have tested it before, cause I'll need to make a new release lol.

For your question, I don't see how it would be possible unfortunately, I would have no way to say what is a twig file and what is a random text :(

**Comment by Chaxwell** [comment]
https://marketplace.visualstudio.com/items?itemName=Chaxwell.twig-link-resolver
