### ISSUE TITLE
Resolve shorthands in file paths

### ISSUE THREAD

**Issue by mndscp** [Chaxwell/vscode-extension-twigLinkResolver#6]
Great idea for an extension!
Liking it a lot but it can't work with my setup yet so here the question about a new feature:

My Twig includes look like this (example code):
```twig
{% if type == 'one' %}
  {% include "@root_components/one.twig" %}
{% else %}
  {% include "@root_components/two.twig" %}
{% endif %}
```

As you can see they have a shorthand for another file path in them. All my includes have that. All shorthands are declared in the project's `composer.json` and they look like this:
```json
"extra": {
  "asset": {
    "twig": {
      "@root_layouts": "somefolder/layouts",
      "@root_components": "somefolder/components",
      "@root_contents": "somefolder/content",
      "@root_templates": "somefolder/templates"
    }
  },
},
```

Unfortuately that makes your extension unable to work with any of my paths.
Two solutions I thought of:
1) Look at `composer.json`, figure out the shorthands and treat them correctly.
2) Make it possible to replace or ignore part of the include paths, in my case `@root_components`, then it would work if I set the correct root path. However as you said that only one root path is possible this would limit everything to one shorthand I guess.

Do you understand my issue and is there anything you can think of that you could do to make it work?
Your extension would certainly make work easier for me and other people I know :)
Thank you in advance, looking forward to your answer!

**Comment by lyrixx** [comment]
IMHO, you should use something similar to `bin/console  debug:twig --format=json | jq '.loader_paths'` to get the namespaces => path mapping

**Comment by mndscp** [comment]
@Chaxwell Is this a silent "won't fix"? Just asking to know :)

Or did I misunderstand the comment above this one and it was a hint on how I can solve this myself?

**Comment by Chaxwell** [comment]
Sorry I have been busy a lot (still am actually).

I don't have an ETA for this issue. But it is definitely something I would like to add to the extension.

The comment from @lyrixx was for me. I like it but it will add a dependency to the Symfony CLI which I'd like to put as an opt-out feature.
I have other plans for this as well.

Thank you for your patience :)

**Comment by MichaelAllenWarner** [comment]
Yes, supporting namespaces would be nice, but I'd suggest that the namespace settings for the extension be configurable via `.vscode/settings.json`, and not rely on the existence of a `composer.json` file. I'm sure I'm not the only one who uses `.twig` files in Node.js (with [Twing](https://gitlab.com/nightlycommit/twing) or [Twig.js](https://github.com/twigjs/twig.js)).
